### ISSUE TITLE
Suggestion: option to have tabs filename focus disabled

### ISSUE THREAD

**Issue by plus-** [jmcalaway/atom-genesis-syntax#1]
It would be nice if you could decide the focus mode of the explorer treeview and the tabs independently.

I like to read my tab names without hovering while still having the focus on the treeview enabled.

**Comment by jeffcalaway** [comment]
Hi plus,

I appreciate your feedback. These sorts of options were always in the plans. I just haven't had the opportunity yet to tinker that far with it. I'll keep this ticket open and report when I've had time to implement something like this. I do agree with you that it is an important feature.

**Comment by jeffcalaway** [comment]
I've updated the Genesis UI to make each bit separately adjustable. Look at the settings page for options. Enjoy!
