### ISSUE TITLE
Last line in text-editor is getting cut off

### ISSUE THREAD

**Issue by HoverBaum** [jmcalaway/atom-genesis-syntax#2]
Still loving this theme a lot, though it seems it is responsible for half cutting off the last line of code in the editor.

![cutoff](https://cloud.githubusercontent.com/assets/7557414/14631229/01d6f658-0645-11e6-8d68-34602f7637ce.png)

I added this to my personal stylesheet to fix it for now:

``` less
atom-pane atom-text-editor {
    padding: 0;
}
```

The padding was added by the genesis-syntax stylesheet. A bit of padding feels like a great idea (especially now mine is gone) but it would be amazing to see the last line of code. It also seemed to do something to the scroll bar. Maybe there is an element that is nested deeper which should have this padding.

**Comment by atomicwrites** [comment]
I was just going to report this issue but I saw you had already done it. I filed a pull request with the fix you found, I just removed the padding in /styles/editor.less.

**Comment by jeffcalaway** [comment]
@HoverBaum @Aventura5 Hey guys, just merged the pull request. Sorry about the wait! Enjoy!
